name: Compilar Blackout

on:
  workflow_dispatch:

jobs:
  build:
    name: Criar APK da Blackout
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compilar Extensao
        run: ./gradlew :src:pt:blackoutcomics:assembleRelease

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Extensao-Blackout
          path: src/pt/blackoutcomics/build/outputs/apk/release/*.apk
